services:
  Vira\Hpropagate\EventListener\RequestListener:
    tags:
      - { name: kernel.event_listener, priority: 256 }

  Vira\Hpropagate\Logger\RequestProcessor:
    arguments:
      - '@request_stack'
    tags:
      - { name: monolog.processor }

  Vira\Hpropagate\Decorator\HttpClient:
    decorates: Symfony\Contracts\HttpClient\HttpClientInterface
    arguments:
      - '@.inner'
      - '@request_stack'
      - '$headersToPropogate'
